[package]
name = "iors"
version = "0.1.0"
authors = ["Mikołaj Robakowski <mikolaj.rob@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.17.0", features = ["invocation"] }

[dev-dependencies]
once_cell = "1.4.1"
test-cdylib = "1.1.0"